# Setup
title:        Gwion Theme
tagline:      A responsive theme for project gwion on GitHub Pages
baseurl:      ""
paginate:     1

# About/contact
author:
  name:       Jérémie Astor
  url:        https://fennecdjay.github.io/Gwion/

# Gems
github: [metadata]
kramdown:
  input: GFM
  hard_wrap: false
gems:
  - jekyll-coffeescript
  - jekyll-paginate


#Others
markdown: kramdown
lsi:  false
safe: true
source: "./."
incremental: false
highlighter: rouge
gist:
  noscript: false
kramdown:
  math_engine: mathjax


#deploy
group: jekyll_plugins do
  gem 'jekyll-deploy'

deploy:
- rsync -aze ssh   
