# Setup
title:        Gwion
tagline:      A strongly timed musical programming language
baseurl:      "https://fennecdjay.github.io/Gwion/"
paginate:     1

# About/contact
author:
  name:       Jérémie Astor
  url:        https://fennecdjay.github.io/Gwion/

# Gems
github: [metadata]

#kramdown:
#  math_engine: mathjax
#  input: GFM
#  hard_wrap: false
#  syntax_highlighter: rouge
gems:
  - jekyll-gist
#  - jekyll-coffeescript
  - jekyll-paginate
#  - redcarpet
gem: 'github-pages'
#gem: 'rouge'
#gem: 'redcarpet'
#Others
markdown: kramdown
#markdown: redcarpet
#lsi:  false
#safe: true
#source: "./."
incremental: false
#highlighter: pygments
#highlighter: rouge
gist:
  noscript: false


#deploy
#group: jekyll_plugins do
#  gem 'jekyll-deploy'

#deploy:
#- rsync -aze ssh   
#gem: "middleman-syntax"



highlighter: rouge
markdown: kramdown
kramdown:
  input: GFM
  auto_ids: true
  syntax_highlighter: rouge
  syntax_highlighter_opts:
    # Use existing pygments syntax highlighting css
    css_class: 'highlight'
